### ISSUE TITLE
Azure /mnt

### ISSUE THREAD

**Issue by patrickmogul** [easy-node-one/validator-toolbox#11]
Azure appears to mount directly to /mnt which is "interesting"

Need to review mount detection and folder placement for stuff that isn't running an internal disk only.

Currently users can create a folder in /mnt with a name before l&f and it will install there and symlink back to ~/harmony

**Comment by cloudstake** [comment]
My current folder, named "harmony_db_0" does come before the "lost+found" folder alphabetically, but script still stops and won't progress. I'll re-do the mount with something earlier in the alphabet. Hope I'm interpreting what you mean by "a name before "l&f".

**Comment by patrickmogul** [comment]
v1.0.1 today looks for only folders that are mount points in /mnt now, no more worries about having other folders as well.

If you have multiple mounts there, i'll have to find a way to deal with that in an upcoming update.
